### ISSUE TITLE
Verbose options seems to be duplicated

### ISSUE THREAD

**Issue by jcoelho93** [asseco-pst/einstein#10]
On the latest development version of Einstein the --verbose option seems to be duplicated.
If you run einstein.exe --help you get the following ERROR:
![image](https://user-images.githubusercontent.com/16445494/63039516-61c56900-bebb-11e9-8f32-85f1947d8c17.png)

**Comment by crisgoncalves** [comment]
Fixed!
Verbose shortcode is now `-v`

![image](https://user-images.githubusercontent.com/2363476/63525669-f8b2a680-c4f5-11e9-8c7c-9a08b1dc728c.png)

`einstein-2.0.0-beta` was also updated.
